/**
 * The fighter rig.
 *
 * Fighters are drawn procedurally from a small skeleton rather than from sprite
 * sheets. That keeps the whole game free of binary art assets — every pixel is
 * generated by this file, so provenance is trivially clean — while still giving
 * each required state a distinct, readable silhouette.
 *
 * Coverage (docs/UI_FLOWS.md lists these as required):
 *   idle with breathing, eight-direction locomotion, high and body versions of
 *   all six punches, high guard, body guard, slip, miss, block, counter,
 *   head-hit and body-hit reactions, stagger, exhaustion, knockdown, the count,
 *   rising, corner, ring introduction, victory and defeat.
 *
 * Nothing here is a placeholder: every state has authored joint positions.
 */
import type Phaser from 'phaser';
import type { ActionState, PunchId, TargetLevel } from '@sim/types';
import { buildFor, paletteFor, skinFor, type BuildProfile, type FighterPalette } from './palettes';

export interface Pose {
  /** 0 upright, 1 fully crouched. */
  crouch: number;
  /** Lateral body lean toward (+1) or away from (-1) the opponent. */
  lean: number;
  /** Head offset from the neck, in local units. */
  headX: number;
  headY: number;
  /** Glove positions in local units, x positive toward the opponent. */
  leadX: number;
  leadY: number;
  rearX: number;
  rearY: number;
  /** Foot positions. */
  frontFootX: number;
  backFootX: number;
  /** Shoulder rotation, radians, positive turns the lead shoulder forward. */
  twist: number;
  /** 0 standing, 1 flat on the canvas. */
  down: number;
  /** Vertical bob applied to the whole figure. */
  bob: number;
  /** Extra arm droop from exhaustion, 0..1. */
  droop: number;
}

const BASE: Pose = {
  crouch: 0,
  lean: 0,
  headX: 1,
  headY: 0,
  leadX: 7,
  leadY: -34,
  rearX: 2,
  rearY: -32,
  frontFootX: 7,
  backFootX: -8,
  twist: 0,
  down: 0,
  bob: 0,
  droop: 0,
};

function pose(p: Partial<Pose>): Pose {
  return { ...BASE, ...p };
}

function blend(a: Pose, b: Pose, t: number): Pose {
  const m = (x: number, y: number): number => x + (y - x) * t;
  return {
    crouch: m(a.crouch, b.crouch),
    lean: m(a.lean, b.lean),
    headX: m(a.headX, b.headX),
    headY: m(a.headY, b.headY),
    leadX: m(a.leadX, b.leadX),
    leadY: m(a.leadY, b.leadY),
    rearX: m(a.rearX, b.rearX),
    rearY: m(a.rearY, b.rearY),
    frontFootX: m(a.frontFootX, b.frontFootX),
    backFootX: m(a.backFootX, b.backFootX),
    twist: m(a.twist, b.twist),
    down: m(a.down, b.down),
    bob: m(a.bob, b.bob),
    droop: m(a.droop, b.droop),
  };
}

// --- Named poses -----------------------------------------------------------

const P = {
  stance: pose({}),
  guard: pose({ leadX: 9, leadY: -41, rearX: -4, rearY: -41, crouch: 0.08, headY: 1 }),
  bodyGuard: pose({ crouch: 0.55, leadX: 9, leadY: -29, rearX: -3, rearY: -28, headY: 2 }),
  crouched: pose({ crouch: 0.5, leadX: 7, leadY: -29, rearX: 2, rearY: -28 }),
  slip: pose({ lean: -0.5, headX: -5, crouch: 0.3, leadX: 5, leadY: -34, rearX: 0, rearY: -33 }),

  // Punch extensions. The lead hand travels further on straight punches; the
  // rear hand rotates the shoulders through.
  jab: pose({ leadX: 27, leadY: -38, rearX: 1, rearY: -39, twist: 0.16, lean: 0.25 }),
  jabBody: pose({ leadX: 24, leadY: -27, rearX: 1, rearY: -37, twist: 0.14, lean: 0.3, crouch: 0.42 }),
  cross: pose({ rearX: 29, rearY: -38, leadX: 3, leadY: -40, twist: 0.5, lean: 0.4 }),
  crossBody: pose({ rearX: 26, rearY: -27, leadX: 3, leadY: -38, twist: 0.46, lean: 0.45, crouch: 0.4 }),
  leadHook: pose({ leadX: 20, leadY: -41, rearX: 1, rearY: -39, twist: 0.3, lean: 0.2 }),
  leadHookBody: pose({ leadX: 18, leadY: -28, rearX: 1, rearY: -38, twist: 0.28, lean: 0.28, crouch: 0.45 }),
  rearHook: pose({ rearX: 23, rearY: -42, leadX: 4, leadY: -38, twist: 0.62, lean: 0.35 }),
  rearHookBody: pose({ rearX: 21, rearY: -28, leadX: 4, leadY: -37, twist: 0.58, lean: 0.4, crouch: 0.44 }),
  leadUpper: pose({ leadX: 15, leadY: -45, rearX: 1, rearY: -38, twist: 0.24, crouch: 0.2, lean: 0.3 }),
  leadUpperBody: pose({ leadX: 14, leadY: -30, rearX: 1, rearY: -37, twist: 0.22, crouch: 0.5, lean: 0.32 }),
  rearUpper: pose({ rearX: 17, rearY: -46, leadX: 4, leadY: -39, twist: 0.55, crouch: 0.24, lean: 0.42 }),
  rearUpperBody: pose({ rearX: 16, rearY: -30, leadX: 4, leadY: -37, twist: 0.52, crouch: 0.5, lean: 0.44 }),

  // Reactions.
  hitHead: pose({ headX: -6, headY: -3, lean: -0.5, leadX: 3, leadY: -31, rearX: -1, rearY: -30, twist: -0.2 }),
  hitBody: pose({ crouch: 0.6, headX: -2, headY: 3, lean: -0.35, leadX: 4, leadY: -26, rearX: 0, rearY: -25 }),
  stagger: pose({ lean: -0.9, headX: -9, headY: 2, crouch: 0.3, leadX: 0, leadY: -26, rearX: -5, rearY: -24, twist: -0.35 }),
  clinch: pose({ lean: 0.55, crouch: 0.2, leadX: 14, leadY: -36, rearX: 12, rearY: -34, headX: 6 }),

  // Grounded.
  down: pose({ down: 1, crouch: 1, leadX: 10, leadY: -6, rearX: -6, rearY: -5, headX: 12, headY: 4, frontFootX: -14, backFootX: -20 }),
  rising: pose({ down: 0.55, crouch: 0.85, leadX: 10, leadY: -14, rearX: -2, rearY: -12, headX: 5, headY: 3, frontFootX: 6, backFootX: -10 }),

  // Ceremony.
  intro: pose({ leadX: 11, leadY: -50, rearX: -6, rearY: -50, headY: -1 }),
  celebrate: pose({ leadX: 6, leadY: -54, rearX: -4, rearY: -54, headY: -2, crouch: -0.06 }),
  defeated: pose({ crouch: 0.75, lean: -0.5, headX: -3, headY: 5, leadX: 2, leadY: -20, rearX: -3, rearY: -19 }),
  corner: pose({ crouch: 0.62, leadX: 4, leadY: -26, rearX: -1, rearY: -25, headY: 2 }),
};

const PUNCH_POSES: Record<PunchId, { head: Pose; body: Pose }> = {
  jab: { head: P.jab, body: P.jabBody },
  cross: { head: P.cross, body: P.crossBody },
  lead_hook: { head: P.leadHook, body: P.leadHookBody },
  rear_hook: { head: P.rearHook, body: P.rearHookBody },
  lead_upper: { head: P.leadUpper, body: P.leadUpperBody },
  rear_upper: { head: P.rearUpper, body: P.rearUpperBody },
};

export interface PoseInput {
  state: ActionState;
  /** Ticks elapsed in the current state. */
  stateTicks: number;
  activePunch: PunchId | null;
  activeLevel: TargetLevel;
  /** Startup / active / recovery lengths in ticks for the current punch. */
  startup: number;
  active: number;
  recovery: number;
  /** Locomotion speed, used for the walk cycle. */
  speed: number;
  /** 0..1 exhaustion; makes the guard sag. */
  exertion: number;
  /** Rise progress while grounded, 0..1. */
  riseProgress: number;
  /** Free-running animation clock in ticks, for idle breathing. */
  clock: number;
}

/** Resolves the pose for a fighter's current simulation state. */
export function resolvePose(i: PoseInput): Pose {
  const breathe = Math.sin(i.clock * 0.055) * 0.7;
  const step = Math.sin(i.clock * 0.28) * Math.min(1, i.speed * 2.2);

  let p: Pose;
  switch (i.state) {
    case 'intro':
      p = P.intro;
      break;
    case 'corner':
      p = P.corner;
      break;
    case 'celebrate':
      p = blend(P.celebrate, P.intro, (Math.sin(i.clock * 0.12) + 1) * 0.25);
      break;
    case 'defeated':
      p = P.defeated;
      break;
    case 'guard':
      p = P.guard;
      break;
    case 'crouch':
      p = P.bodyGuard;
      break;
    case 'slip':
      p = blend(P.stance, P.slip, Math.min(1, i.stateTicks / 4));
      break;
    case 'clinch':
      p = P.clinch;
      break;
    case 'hit_light':
      p = blend(P.hitHead, P.stance, Math.min(1, i.stateTicks / 9));
      break;
    case 'hit_heavy':
      p = blend(P.hitHead, P.stance, Math.min(1, i.stateTicks / 17));
      break;
    case 'stagger':
      p = blend(P.stagger, P.stance, Math.min(1, i.stateTicks / 30));
      break;
    case 'knockdown':
      p = blend(P.stance, P.down, Math.min(1, i.stateTicks / 12));
      break;
    case 'rising':
      p = blend(P.down, P.rising, Math.min(1, i.stateTicks / 20));
      break;
    case 'knocked_out':
      p = P.down;
      break;
    case 'punch_startup':
    case 'punch_active':
    case 'punch_recover': {
      const punch = i.activePunch ? PUNCH_POSES[i.activePunch] : PUNCH_POSES.jab;
      const target = i.activeLevel === 'body' ? punch.body : punch.head;
      if (i.state === 'punch_startup') {
        // Wind up: pull back slightly, then drive forward.
        const t = i.startup > 0 ? i.stateTicks / i.startup : 1;
        const wind = pose({ ...P.guard, leadX: P.guard.leadX - 3, rearX: P.guard.rearX - 4, twist: -0.12 });
        p = blend(wind, target, t * t);
      } else if (i.state === 'punch_active') {
        p = target;
      } else {
        const t = i.recovery > 0 ? Math.min(1, i.stateTicks / i.recovery) : 1;
        p = blend(target, P.guard, t);
      }
      break;
    }
    case 'move':
      p = pose({ ...P.stance, frontFootX: BASE.frontFootX + step * 3, backFootX: BASE.backFootX - step * 3 });
      break;
    case 'idle':
    default:
      p = pose({ ...P.stance, bob: breathe });
      break;
  }

  // Exhaustion sags the hands. It is never total — see COMBAT_SPEC.
  const droop = Math.min(1, i.exertion);
  if (droop > 0.05 && p.down < 0.5) {
    p = {
      ...p,
      leadY: p.leadY + droop * 4.5,
      rearY: p.rearY + droop * 4.5,
      crouch: p.crouch + droop * 0.06,
      droop,
    };
  }
  if (i.state === 'idle' || i.state === 'move' || i.state === 'guard') {
    p = { ...p, bob: p.bob + breathe * 0.6 };
  }
  return p;
}

// ---------------------------------------------------------------------------
// Drawing
// ---------------------------------------------------------------------------

export interface BoxerAppearance {
  paletteKey: string;
  skinKey: string;
  buildKey: string;
  trunksKey: string;
  hairKey: string;
}

/** Two-bone solve so elbows and knees bend the right way. */
function elbow(sx: number, sy: number, hx: number, hy: number, len: number, bend: number): [number, number] {
  const dx = hx - sx;
  const dy = hy - sy;
  const d = Math.max(0.001, Math.sqrt(dx * dx + dy * dy));
  const half = Math.min(len, d) * 0.5;
  const mx = sx + dx * 0.5;
  const my = sy + dy * 0.5;
  // Offset perpendicular to the limb, scaled by how folded it is.
  const slack = Math.max(0, len - d) * 0.5 + 1.2;
  const nx = -dy / d;
  const ny = dx / d;
  return [mx + nx * slack * bend, my + ny * slack * bend + half * 0.02];
}

function limb(
  g: Phaser.GameObjects.Graphics,
  ax: number,
  ay: number,
  bx: number,
  by: number,
  width: number,
  colour: number,
): void {
  g.lineStyle(width, colour, 1);
  g.beginPath();
  g.moveTo(ax, ay);
  g.lineTo(bx, by);
  g.strokePath();
}

/** Draws the trunks pattern. Patterns are geometry, never textures. */
function drawTrunks(
  g: Phaser.GameObjects.Graphics,
  hipY: number,
  w: number,
  h: number,
  pal: FighterPalette,
  pattern: string,
  facing: number,
): void {
  g.fillStyle(pal.primary, 1);
  g.fillRect(-w * 0.5, hipY, w, h);

  g.fillStyle(pal.accent, 1);
  switch (pattern) {
    case 'stripe':
      g.fillRect(-w * 0.12, hipY, w * 0.24, h);
      break;
    case 'sash':
      g.fillTriangle(-w * 0.5, hipY + h, -w * 0.5 + w * 0.45, hipY, -w * 0.5 + w * 0.75, hipY);
      break;
    case 'chevron':
      g.fillTriangle(0, hipY + h * 0.25, -w * 0.5, hipY + h * 0.75, w * 0.5, hipY + h * 0.75);
      break;
    case 'flame':
      for (let k = 0; k < 3; k++) {
        const fx = -w * 0.4 + k * w * 0.34;
        g.fillTriangle(fx, hipY + h, fx + w * 0.12, hipY + h * 0.2, fx + w * 0.24, hipY + h);
      }
      break;
    case 'diamond':
      g.fillTriangle(0, hipY + h * 0.15, -w * 0.22, hipY + h * 0.55, 0, hipY + h * 0.95);
      g.fillTriangle(0, hipY + h * 0.15, w * 0.22, hipY + h * 0.55, 0, hipY + h * 0.95);
      break;
    case 'bolt':
      g.fillTriangle(-w * 0.08 * facing, hipY, w * 0.22 * facing, hipY + h * 0.45, -w * 0.02 * facing, hipY + h * 0.45);
      g.fillTriangle(-w * 0.02 * facing, hipY + h * 0.45, w * 0.16 * facing, hipY + h, -w * 0.2 * facing, hipY + h * 0.55);
      break;
    case 'crown':
      g.fillRect(-w * 0.5, hipY, w, h * 0.22);
      for (let k = 0; k < 4; k++) {
        g.fillTriangle(-w * 0.5 + k * w * 0.25, hipY + h * 0.22, -w * 0.5 + (k + 0.5) * w * 0.25, hipY + h * 0.55, -w * 0.5 + (k + 1) * w * 0.25, hipY + h * 0.22);
      }
      break;
    case 'block':
    default:
      g.fillRect(-w * 0.5, hipY + h * 0.72, w, h * 0.28);
      break;
  }
  // Waistband reads as a silhouette break at small sizes.
  g.fillStyle(pal.accent, 1);
  g.fillRect(-w * 0.5, hipY - 1.5, w, 2.5);
}

/**
 * Renders one fighter into an already-translated, already-scaled Graphics
 * object. The caller sets position, scale and flip.
 */
export function drawBoxer(
  g: Phaser.GameObjects.Graphics,
  p: Pose,
  look: BoxerAppearance,
  opts: { hurtFlash?: number; outlineOnly?: boolean; colorSafe?: boolean } = {},
): void {
  const pal = paletteFor(look.paletteKey);
  const skin = skinFor(look.skinKey);
  const build: BuildProfile = buildFor(look.buildKey);

  const flash = opts.hurtFlash ?? 0;
  const skinBase = flash > 0 ? mix(skin.base, 0xffffff, flash) : skin.base;

  const crouchY = p.crouch * 8;
  const bodyY = p.bob + crouchY;
  const lean = p.lean * 3;

  const hipY = -20 * build.height + bodyY;
  const chestY = -32 * build.height + bodyY;
  const neckY = -40 * build.height + bodyY;
  const headYc = neckY - 5 + p.headY;
  const headXc = p.headX + lean * 1.4;

  const shoulderW = 8.5 * build.shoulder;
  const torsoW = 13 * build.torso;
  const limbW = 3.6 * build.limb;

  // --- Legs ------------------------------------------------------------
  const groundY = 0;
  if (p.down < 0.6) {
    const kneeBend = 0.6 + p.crouch * 0.5;
    const [fkx, fky] = elbow(lean * 0.5, hipY, p.frontFootX, groundY, 26 * build.height, kneeBend);
    const [bkx, bky] = elbow(lean * 0.5, hipY, p.backFootX, groundY, 26 * build.height, -kneeBend);
    limb(g, lean * 0.5, hipY, bkx, bky, limbW * 1.25, skin.shade);
    limb(g, bkx, bky, p.backFootX, groundY, limbW * 1.1, skin.shade);
    limb(g, lean * 0.5, hipY, fkx, fky, limbW * 1.3, skinBase);
    limb(g, fkx, fky, p.frontFootX, groundY, limbW * 1.15, skinBase);
    // Boots.
    g.fillStyle(pal.glove, 1);
    g.fillRect(p.backFootX - 3.5, groundY - 3, 8, 3.5);
    g.fillRect(p.frontFootX - 3.5, groundY - 3, 8, 3.5);
  } else {
    // On the canvas: the body lies along the floor.
    limb(g, lean, hipY, p.frontFootX, groundY - 2, limbW * 1.3, skinBase);
    limb(g, lean, hipY, p.backFootX, groundY - 1, limbW * 1.2, skin.shade);
    g.fillStyle(pal.glove, 1);
    g.fillRect(p.frontFootX - 4, groundY - 4, 8, 3.5);
  }

  // --- Trunks ----------------------------------------------------------
  drawTrunks(g, hipY - 1, torsoW * 1.15, 12, pal, look.trunksKey, 1);

  // --- Torso -----------------------------------------------------------
  const twistScale = 1 - Math.abs(p.twist) * 0.28;
  g.fillStyle(skinBase, 1);
  g.fillTriangle(-torsoW * 0.5 * twistScale + lean, chestY, torsoW * 0.5 * twistScale + lean, chestY, -torsoW * 0.55, hipY + 2);
  g.fillTriangle(torsoW * 0.5 * twistScale + lean, chestY, torsoW * 0.55, hipY + 2, -torsoW * 0.55, hipY + 2);
  // Chest shading gives the silhouette depth at 640x360.
  g.fillStyle(skin.shade, 0.5);
  g.fillTriangle(-torsoW * 0.5 * twistScale + lean, chestY, -torsoW * 0.1 + lean, chestY, -torsoW * 0.55, hipY + 2);

  // --- Arms ------------------------------------------------------------
  const rearShX = -shoulderW * 0.55 + lean - p.twist * 4;
  const leadShX = shoulderW * 0.55 + lean + p.twist * 4;
  const shY = chestY + 1;
  const armLen = 22 * build.height;

  // Rear arm is drawn behind the torso.
  const [rex, rey] = elbow(rearShX, shY, p.rearX, p.rearY + bodyY, armLen, -0.9);
  limb(g, rearShX, shY, rex, rey, limbW, skin.shade);
  limb(g, rex, rey, p.rearX, p.rearY + bodyY, limbW * 0.95, skin.shade);
  g.fillStyle(darken(pal.glove, 0.22), 1);
  g.fillCircle(p.rearX, p.rearY + bodyY, 4.1 * build.limb);

  // --- Head ------------------------------------------------------------
  g.fillStyle(skinBase, 1);
  g.fillCircle(headXc, headYc, 6.2 * build.height);
  g.fillStyle(skin.shade, 0.45);
  g.fillCircle(headXc - 2.2, headYc + 0.6, 4.6 * build.height);
  // Hair.
  const hairColour = look.hairKey === 'bald' ? skin.shade : (0x2a1f18 ^ (hashKey(look.hairKey) & 0x1f1f1f));
  if (look.hairKey !== 'bald') {
    g.fillStyle(hairColour, 1);
    const cap = look.hairKey === 'wave' || look.hairKey === 'slick' ? 5.0 : 4.2;
    g.fillCircle(headXc - 0.6, headYc - 2.4, cap * build.height);
  }
  // A face marker so facing is unambiguous even in silhouette.
  g.fillStyle(0x10131a, 0.85);
  g.fillRect(headXc + 3.0, headYc - 1.2, 2.2, 1.4);

  // --- Lead arm, drawn in front ----------------------------------------
  const [lex, ley] = elbow(leadShX, shY, p.leadX, p.leadY + bodyY, armLen, -1.0);
  limb(g, leadShX, shY, lex, ley, limbW * 1.05, skinBase);
  limb(g, lex, ley, p.leadX, p.leadY + bodyY, limbW, skinBase);
  g.fillStyle(pal.glove, 1);
  g.fillCircle(p.leadX, p.leadY + bodyY, 4.3 * build.limb);
  g.fillStyle(pal.accent, 0.9);
  g.fillCircle(p.leadX - 1.2, p.leadY + bodyY - 1.2, 1.6 * build.limb);

  // A colour-safe outline keeps fighters separable without relying on hue.
  if (opts.colorSafe) {
    g.lineStyle(1, pal.outline, 0.9);
    g.strokeCircle(headXc, headYc, 6.4 * build.height);
    g.strokeCircle(p.leadX, p.leadY + bodyY, 4.9 * build.limb);
    g.strokeCircle(p.rearX, p.rearY + bodyY, 4.7 * build.limb);
  }
}

function mix(a: number, b: number, t: number): number {
  const ar = (a >> 16) & 0xff;
  const ag = (a >> 8) & 0xff;
  const ab = a & 0xff;
  const br = (b >> 16) & 0xff;
  const bg = (b >> 8) & 0xff;
  const bb = b & 0xff;
  const r = Math.round(ar + (br - ar) * t);
  const gg = Math.round(ag + (bg - ag) * t);
  const bl = Math.round(ab + (bb - ab) * t);
  return (r << 16) | (gg << 8) | bl;
}

function darken(c: number, t: number): number {
  return mix(c, 0x000000, t);
}

function hashKey(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return h >>> 0;
}

/** Portrait rendering for menus, using the same rig so nothing can drift. */
export function drawPortrait(g: Phaser.GameObjects.Graphics, look: BoxerAppearance, scale: number): void {
  g.save();
  g.scaleCanvas(scale, scale);
  drawBoxer(g, P.intro, look, {});
  g.restore();
}

export const POSES = P;
