/**
 * Career data contracts.
 *
 * The career is a deterministic state machine driven by a seeded RNG, exactly
 * like the bout simulation. Given the same seed and the same player decisions,
 * a career replays identically — which is what makes the developer
 * fast-forward tool and the progression tests meaningful.
 */
import type { ArchetypeId, CoreRatings, FighterDefinition, OutcomeKind, SecondaryRatings } from '@sim/types';
import type { RngState } from '@sim/rng';
import type { DifficultyId } from '@ai/profiles';

/** Where the player is in the career loop. */
export type CareerPhase =
  | 'hub'
  | 'select_opponent'
  | 'pre_fight'
  | 'in_fight'
  | 'post_fight'
  | 'training'
  | 'challenge'
  | 'retired';

export type CareerStage = 'prospect' | 'developing' | 'prime' | 'veteran' | 'declining';

/** A fighter's standing in the career world. */
export interface LadderEntry {
  fighterId: string;
  rank: number;
  wins: number;
  losses: number;
  draws: number;
  kos: number;
  /** Bouts contested in this career world. */
  bouts: number;
  age: number;
  /** Recent results, most recent last. `W`, `L`, `D`. */
  form: string[];
  /** Retired fighters stay in the record but leave the ladder. */
  retired: boolean;
  /** Cumulative career earnings, used for the legacy board. */
  earnings: number;
  /** Long-term wear. Rises with bouts and damage; drives decline. */
  wear: number;
}

/** One completed bout in the player's record. */
export interface BoutRecord {
  index: number;
  opponentId: string;
  opponentName: string;
  playerRankBefore: number;
  opponentRankBefore: number;
  playerRankAfter: number;
  rounds: number;
  venueId: string;
  result: 'win' | 'loss' | 'draw';
  kind: OutcomeKind;
  reasonKey: string;
  endedRound: number;
  purse: number;
  /** Judges' totals, player first. */
  scorecards: [number, number][];
  titleBout: boolean;
  seed: number;
}

/** A single offered training item. */
export interface TrainingOption {
  id: string;
  nameKey: string;
  descriptionKey: string;
  /** Attribute deltas actually applied, after diminishing returns. */
  gains: Partial<CoreRatings>;
  /** Secondary attribute deltas. */
  secondaryGains: Partial<SecondaryRatings>;
  /** Extra wear this option costs. Hard training is not free. */
  wearCost: number;
  /** Archetype this option synergises with, for the UI hint. */
  synergy: ArchetypeId | null;
}

export interface PendingChallenge {
  challengerId: string;
  challengerName: string;
  challengerRank: number;
  rounds: number;
  purse: number;
  /** Refusing costs the player this rank. */
  refusalRank: number;
}

/** The complete, serialisable career. */
export interface CareerState {
  /** Schema version; migrations key off this. */
  version: number;
  seed: number;
  rngState: RngState;
  createdAtBout: number;

  phase: CareerPhase;
  difficulty: DifficultyId;

  /** The player's boxer. Ratings mutate as they train and age. */
  player: FighterDefinition;
  playerRank: number;
  /** Rank the player must beat to hold the title. Always 1. */
  titleHolderId: string;
  /** True once the player has taken the title. */
  isChampion: boolean;
  titleDefences: number;

  boutIndex: number;
  wins: number;
  losses: number;
  draws: number;
  kos: number;
  consecutiveLosses: number;
  earnings: number;
  availableFunds: number;
  wear: number;
  stage: CareerStage;

  ladder: LadderEntry[];
  history: BoutRecord[];
  /** Opponents legally selectable right now. */
  offeredOpponents: string[];
  /** Training slate awaiting a choice, and how many picks remain. */
  trainingSlate: TrainingOption[];
  trainingPicks: number;
  trainingLog: string[];
  pendingChallenge: PendingChallenge | null;

  /**
   * Whether the one-time career rebuild has been used. A losing run gets a
   * single documented route back rather than being deleted outright.
   */
  rebuildUsed: boolean;
  /** Set once the career is over. */
  ending: CareerEnding | null;
  /** News lines generated by the world simulation, newest first. */
  news: string[];
}

export interface CareerEnding {
  reasonKey: 'ending.boutLimit' | 'ending.lossStreak' | 'ending.voluntary' | 'ending.refusedChallenge';
  finalRank: number;
  wasChampion: boolean;
  titleDefences: number;
  earnings: number;
  record: { wins: number; losses: number; draws: number; kos: number };
  /** Letter grade derived from the whole career. */
  gradeKey: string;
  boutsFought: number;
}

/** A retired career preserved on the legacy board. */
export interface LegacyRecord {
  name: string;
  nickname: string;
  earnings: number;
  wins: number;
  losses: number;
  draws: number;
  kos: number;
  peakRank: number;
  titleDefences: number;
  gradeKey: string;
  /** Ruleset label so an assisted career never silently overwrites a standard one. */
  difficulty: DifficultyId;
}

/** Career-wide tuning. See docs/CAREER_SPEC.md. */
export const CAREER_RULES = {
  /** Hard cap. Every career ends here. */
  maxBouts: 20,
  /** Bout index after which decline begins. */
  agingStartsAt: 12,
  /** Consecutive losses that force retirement. */
  forcedRetirementLossStreak: 4,
  /**
   * Before this bout, hitting the loss streak once triggers a rebuild instead
   * of retirement: the fighter drops to the foot of the ladder and the streak
   * clears. Documented recovery rule (docs/CAREER_SPEC.md).
   */
  rebuildAvailableBefore: 12,
  /** Ranks above the player they may challenge after a win. */
  challengeUpAfterWin: 3,
  /** Ranks above the player they may challenge for their first bout. */
  challengeUpFirstBout: 2,
  /** Ranks above the player they may challenge after a loss. */
  challengeUpAfterLoss: 1,
  /** Training picks awarded. */
  picksOnWin: 3,
  picksOnLoss: 2,
  picksOnDraw: 2,
  /** Size of the training slate offered. */
  slateSize: 5,
  /** Rating above which training returns diminish sharply. */
  softCap: 78,
  /** Absolute rating ceiling. */
  hardCap: 96,
  /** The legacy benchmark to beat, in whole currency units. */
  legacyTarget: 8_000_000,
} as const;
