/**
 * Content validation, run before every production build.
 *
 * Because all art and audio are generated by code rather than loaded from
 * files, "asset validation" here means checking that every generated asset
 * *definition* is complete and consistent: every animation state a fighter can
 * enter has an authored pose, every content id is unique, every string key
 * referenced by data resolves, and every media entry has a ledger row.
 */
import { readFileSync, existsSync } from 'node:fs';
import { ROSTER } from '../src/data/fighters';
import { VENUES } from '../src/data/venues';
import { getPunch } from '../src/data/punches';
import { AI_PROFILES } from '../src/ai/profiles';
import { STRINGS } from '../src/ui/strings';
import { ACTIONS, DEFAULT_GAMEPAD, DEFAULT_KEYBOARD } from '../src/input/actions';
import { BUILDS, FIGHTER_PALETTES, HAIR_STYLES, SKIN_TONES, TRUNK_PATTERNS } from '../src/art/palettes';
import { resolvePose } from '../src/art/boxer';
import { TRAINING_CATALOGUE_IDS } from '../src/career/training';
import { STYLE_BASES } from '../src/career/creation';
import { PUNCH_IDS, type ActionState, type TargetLevel } from '../src/sim/types';
import { documentedClaims } from './balance-targets';

const problems: string[] = [];
const notes: string[] = [];

function check(condition: boolean, message: string): void {
  if (!condition) problems.push(message);
}

// --- Every fighter animation state must have an authored pose ---------------

const ALL_STATES: ActionState[] = [
  'idle', 'move', 'guard', 'crouch', 'punch_startup', 'punch_active', 'punch_recover',
  'slip', 'hit_light', 'hit_heavy', 'stagger', 'clinch', 'knockdown', 'rising',
  'knocked_out', 'corner', 'intro', 'celebrate', 'defeated',
];

for (const state of ALL_STATES) {
  for (const punch of [null, ...PUNCH_IDS]) {
    for (const level of ['head', 'body'] as TargetLevel[]) {
      const pose = resolvePose({
        state,
        stateTicks: 3,
        activePunch: punch,
        activeLevel: level,
        startup: 8,
        active: 3,
        recovery: 12,
        speed: 0.5,
        exertion: 0.4,
        riseProgress: 0.3,
        clock: 17,
      });
      for (const [k, v] of Object.entries(pose)) {
        if (!Number.isFinite(v)) problems.push(`pose ${state}/${punch}/${level} has a non-finite ${k}`);
      }
      // A pose that never moves the hands from the base stance would be a
      // placeholder; every state must be visually distinct in some way.
      check(
        Math.abs(pose.leadX) + Math.abs(pose.leadY) > 0,
        `pose ${state} appears to be empty`,
      );
    }
  }
}
notes.push(`${ALL_STATES.length} fighter states x ${PUNCH_IDS.length + 1} punches x 2 levels resolved to finite poses`);

// --- Ids and references ----------------------------------------------------

check(new Set(ROSTER.map((f) => f.id)).size === ROSTER.length, 'duplicate fighter id');
check(new Set(ROSTER.map((f) => f.displayName)).size === ROSTER.length, 'duplicate fighter name');
check(new Set(VENUES.map((v) => v.id)).size === VENUES.length, 'duplicate venue id');
check(new Set(TRAINING_CATALOGUE_IDS).size === TRAINING_CATALOGUE_IDS.length, 'duplicate training id');
check(new Set(STYLE_BASES.map((s) => s.archetype)).size === STYLE_BASES.length, 'duplicate style base');

for (const f of ROSTER) {
  check(AI_PROFILES[f.style.archetype] !== undefined, `${f.id}: no AI profile for ${f.style.archetype}`);
  check(FIGHTER_PALETTES[f.appearance.paletteKey] !== undefined, `${f.id}: unknown palette ${f.appearance.paletteKey}`);
  check(SKIN_TONES[f.appearance.skinKey] !== undefined, `${f.id}: unknown skin ${f.appearance.skinKey}`);
  check(BUILDS[f.appearance.buildKey] !== undefined, `${f.id}: unknown build ${f.appearance.buildKey}`);
  check((TRUNK_PATTERNS as readonly string[]).includes(f.appearance.trunksKey), `${f.id}: unknown trunks ${f.appearance.trunksKey}`);
  check((HAIR_STYLES as readonly string[]).includes(f.appearance.hairKey), `${f.id}: unknown hair ${f.appearance.hairKey}`);
  check(STRINGS[f.scoutKey] !== undefined, `${f.id}: missing scouting string ${f.scoutKey}`);
}

for (const v of VENUES) {
  check(STRINGS[v.nameKey] !== undefined, `venue ${v.id}: missing ${v.nameKey}`);
  check(STRINGS[v.descriptionKey] !== undefined, `venue ${v.id}: missing ${v.descriptionKey}`);
}

for (const id of PUNCH_IDS) {
  for (const level of ['head', 'body'] as TargetLevel[]) {
    const p = getPunch(id, level);
    check(STRINGS[p.nameKey] !== undefined, `punch ${id}: missing ${p.nameKey}`);
    check(p.reach > p.minRange, `punch ${id}/${level}: reach does not exceed minimum range`);
    check(p.vulnerableTo > p.vulnerableFrom, `punch ${id}/${level}: empty vulnerability window`);
  }
}

for (const a of ACTIONS) {
  check(Boolean(DEFAULT_KEYBOARD[a]), `action ${a}: no default keyboard binding`);
  check(Boolean(DEFAULT_GAMEPAD[a]), `action ${a}: no default gamepad binding`);
  check(STRINGS[`action.${a}`] !== undefined, `action ${a}: missing label`);
}

for (const id of TRAINING_CATALOGUE_IDS) {
  check(STRINGS[`training.${id}.name`] !== undefined, `training ${id}: missing name`);
  check(STRINGS[`training.${id}.desc`] !== undefined, `training ${id}: missing description`);
}

for (const [k, v] of Object.entries(STRINGS)) {
  check(v.trim().length > 0, `string ${k} is empty`);
}

// --- Provenance -------------------------------------------------------------

const LEDGER = 'docs/LEGAL_AND_ASSET_LEDGER.md';
check(existsSync(LEDGER), `${LEDGER} is missing — asset provenance is a release blocker`);
if (existsSync(LEDGER)) {
  const ledger = readFileSync(LEDGER, 'utf8');
  check(/BUILD_PROFILE\s*[:|]\s*\**SAFE_RELEASE/.test(ledger), `${LEDGER} does not record the active build profile`);
}

// --- Documented balance claims match the enforced targets -------------------
//
// The failure this exists to prevent: prose claiming a 40–60% archetype band
// while the gate asserted 20–80%, for the whole project, with nothing failing.
// Every quantitative balance claim in the documentation is now generated from
// tools/balance-targets.ts, and this check fails the build if the two disagree
// — so a target cannot be widened without the sentence changing to match, and
// a sentence cannot be written that no test enforces.

const BALANCE_DOCS = ['CLAUDE.md', 'docs/PRODUCT_CANON.md', 'docs/COMBAT_SPEC.md'];
for (const doc of BALANCE_DOCS) {
  if (!existsSync(doc)) {
    check(false, `${doc} is missing — the balance targets have nowhere to be stated`);
    continue;
  }
  const text = readFileSync(doc, 'utf8');
  for (const claim of documentedClaims()) {
    check(
      text.includes(claim.text),
      `${doc} does not state the enforced ${claim.label} ("${claim.text}") — ` +
        `documentation and tools/balance-targets.ts have drifted apart`,
    );
  }
}
notes.push(`balance claims in ${BALANCE_DOCS.join(', ')} match tools/balance-targets.ts`);

// --- Report -----------------------------------------------------------------

for (const n of notes) console.log(`  · ${n}`);
if (problems.length > 0) {
  console.error(`\ncontent validation failed (${problems.length}):`);
  for (const p of problems) console.error(`  - ${p}`);
  process.exit(1);
}
console.log(`  · ${ROSTER.length} fighters, ${VENUES.length} venues, ${PUNCH_IDS.length * 2} moves, ${Object.keys(STRINGS).length} strings validated`);
console.log('content validation passed');
