/**
 * Three original venues. Each has its own palette, crowd character and
 * ambience; they share the ring geometry defined in `@sim/types` so that the
 * simulation is identical wherever a bout is staged.
 *
 * All names, colours and descriptions are original to this project.
 */
export interface VenueDefinition {
  id: string;
  nameKey: string;
  /** Ring-apron and turnbuckle colours. */
  palette: {
    /** Deep background wash. */
    backdrop: number;
    /** Crowd silhouette bands, far to near. */
    crowd: [number, number, number];
    /** Canvas colour. */
    canvas: number;
    /** Canvas shading under the fighters. */
    canvasShade: number;
    apron: number;
    rope: [number, number, number];
    post: number;
    /** Spotlight tint. */
    light: number;
    /** Accent used by the venue's HUD trim. */
    accent: number;
  };
  /** Crowd loudness floor, 0..1. Small halls are quieter. */
  crowdBase: number;
  /** How sharply the crowd reacts to clean punches, 0..1. */
  crowdVolatility: number;
  /** Music track key generated by the synth. */
  musicKey: 'gym' | 'arena' | 'coliseum';
  /** Rows of crowd drawn behind the ring. */
  crowdRows: number;
  /** Whether hanging lights and haze are drawn. */
  haze: boolean;
  descriptionKey: string;
}

export const VENUES: readonly VenueDefinition[] = [
  {
    id: 'ironworks',
    nameKey: 'venue.ironworks.name',
    descriptionKey: 'venue.ironworks.desc',
    palette: {
      backdrop: 0x140f14,
      crowd: [0x241a24, 0x33253a, 0x453156],
      canvas: 0xc9c3b6,
      canvasShade: 0x9d9789,
      apron: 0x3a2a46,
      rope: [0xd8d2c4, 0xc0392b, 0xd8d2c4],
      post: 0x6b5b73,
      light: 0xfff2d6,
      accent: 0xe08a3c,
    },
    crowdBase: 0.28,
    crowdVolatility: 0.55,
    musicKey: 'gym',
    crowdRows: 3,
    haze: true,
  },
  {
    id: 'harbourdome',
    nameKey: 'venue.harbourdome.name',
    descriptionKey: 'venue.harbourdome.desc',
    palette: {
      backdrop: 0x0b1420,
      crowd: [0x14202f, 0x1d2d42, 0x274058],
      canvas: 0xdfe3e6,
      canvasShade: 0xa8b0b8,
      apron: 0x1b3450,
      rope: [0xf0f4f7, 0x2e86c1, 0xf0f4f7],
      post: 0x4a6b8a,
      light: 0xe8f4ff,
      accent: 0x3fa9d6,
    },
    crowdBase: 0.42,
    crowdVolatility: 0.72,
    musicKey: 'arena',
    crowdRows: 4,
    haze: false,
  },
  {
    id: 'goldreef',
    nameKey: 'venue.goldreef.name',
    descriptionKey: 'venue.goldreef.desc',
    palette: {
      backdrop: 0x1a1206,
      crowd: [0x2a1e0c, 0x3d2c12, 0x54401d],
      canvas: 0xf2e6c8,
      canvasShade: 0xc0ae8b,
      apron: 0x4a3413,
      rope: [0xfff4d4, 0xb8912f, 0xfff4d4],
      post: 0x8a6d2a,
      light: 0xfff0c0,
      accent: 0xe0b93c,
    },
    crowdBase: 0.55,
    crowdVolatility: 0.9,
    musicKey: 'coliseum',
    crowdRows: 5,
    haze: true,
  },
];

export function getVenue(id: string): VenueDefinition {
  const v = VENUES.find((x) => x.id === id);
  if (!v) throw new Error(`Unknown venue: ${id}`);
  return v;
}
